// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKhxuO7bqZme9_p-0FP49339aqcgxsoQ',
    appId: '1:456408330601:web:f53b48337f0bad2de0cdf8',
    messagingSenderId: '456408330601',
    projectId: 'spruuk',
    authDomain: 'spruuk.firebaseapp.com',
    storageBucket: 'spruuk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABE5jbm1TcfBJKZbO7wfwbdf96HtMOvC4',
    appId: '1:456408330601:android:e64b94efc2f64b0ce0cdf8',
    messagingSenderId: '456408330601',
    projectId: 'spruuk',
    storageBucket: 'spruuk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK54rxKx-MeCeAtpTlnvXGLQpUDambvpI',
    appId: '1:456408330601:ios:e70c053f131d91b2e0cdf8',
    messagingSenderId: '456408330601',
    projectId: 'spruuk',
    storageBucket: 'spruuk.appspot.com',
    iosClientId: '456408330601-ft8f17uk5k3necanmuiiov97u7g3hg1f.apps.googleusercontent.com',
    iosBundleId: 'spruuk.com.spruuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK54rxKx-MeCeAtpTlnvXGLQpUDambvpI',
    appId: '1:456408330601:ios:e70c053f131d91b2e0cdf8',
    messagingSenderId: '456408330601',
    projectId: 'spruuk',
    storageBucket: 'spruuk.appspot.com',
    iosClientId: '456408330601-ft8f17uk5k3necanmuiiov97u7g3hg1f.apps.googleusercontent.com',
    iosBundleId: 'spruuk.com.spruuk',
  );
}
